### ISSUE TITLE
export test helpers for downstream consumers

### ISSUE THREAD

**Issue by bantic** [bustlelabs/ember-mobiledoc-editor#100]
For apps that depend on ember-mobiledoc-editor, documenting and exporting test-helpers (like `runLater` and `moveCursorTo`) would make development easier.

**Comment by bantic** [comment]
High-level acceptance test level helpers would also be good (like `insertText(editorElement, 'sometext')`, or simply making it so that `fillIn` works with an editor element)

**Comment by chrisdpeters** [comment]
@bantic Do you have any suggestions for workarounds for acceptance testing? I am finding that I need to just skip acceptance tests for anything non-trivial involving ember-mobiledoc-editor for now because I can't seem to be able to interact with the editor at all.

I'm not really trying to test specific editor functionality but would like to test overall acceptance scenarios like basic updates to the content, calling the update endpoint, and updating the overall UI with flash notifications, etc.

**Comment by bantic** [comment]
@chrisdpeters If you are testing basic scenarios of the form "no-content"->"any-content" and vice versa, modifying the dom in the editor directly should be ok to do, but you may run into some trouble due to the async nature of the code here. I will play around with this a bit and make a specific suggestion.

**Comment by bantic** [comment]
@chrisdpeters I think we can actually keep an internal reference to the editor instance in tests, and export a test helper that accesses it and can update the editor...I will make a spike on this tomorrow.
