### ISSUE TITLE
Extensible markup attributes

### ISSUE THREAD

**Issue by ef4** [bustlelabs/ember-mobiledoc-editor#62]
I use a custom widget for adding links that accepts both a URL and a checkbox for "Open in New Window". Then I do `postEditor.builder.createMarkup('a', { href, target })`. And this is all working great, except I needed to do this:

```js
import { VALID_ATTRIBUTES } from 'mobiledoc-kit/models/markup';
VALID_ATTRIBUTES.push('target');
```

Mutating a list in another module seems bad. Should we offer a different way to extend this?

Whitelisting additional attributes seems like a progressive-enhancement-friendly way of extending mobiledoc. Implementations that don't trust the same set of attributes as you do can ignore them.

**Comment by bantic** [comment]
There's a similar, relevant conversation about section tagNames happening at https://github.com/bustlelabs/mobiledoc-kit/issues/342 as well.

I like the idea of progressive-enhancement-friendly extending. There is some concern (discussed at length in the above thread) that this can damage the portability of mobiledocs — it becomes difficult to be certain that you have configured/extended your renderer properly to account for all the markup attributes (or section tag names) that a 2nd party's mobiledocs might include.

I would be open to exposing a method to register additional valid attributes on a renderer.
cc @mixonic

**Comment by bantic** [comment]
(off-topic but whitelisting `target="blank"` [may be dangerous](https://mathiasbynens.github.io/rel-noopener/))

**Comment by ef4** [comment]
Oh yes, apologies, I meant to file this issue on mobiledoc-kit anyway, since it clearly belongs there.

**Comment by sdhull** [comment]
@ef4 I know it's 2 years later -- sorry -- but how did you deal modifying `VALID_ATTRIBUTES` in a rendering context? I've added `<small>` to `VALID_MARKUP_TAGNAMES` and it works fine in an editor but not so much in `mobiledoc-dom-renderer`

**Comment by ef4** [comment]
I don't remember exactly but I don't think I had to modify the renderer just to support an additional attribute on `<a>`. Adding more tags is different, and not what I was doing here.

**Comment by sdhull** [comment]
Darn, OK. Thanks for replying. I've been through the code more times than I care to admit and I finally broke down and forked the renderer (and ember renderer addon). 😐

**Comment by ef4** [comment]
If you write up what you're trying to do on https://discuss.emberjs.com/ I can try to help.

**Comment by sdhull** [comment]
I'm afraid It's really more about mobiledoc than ember. And it's really just that I'm trying to add `<small>` tag to my editor & renderer (adding it to the editor, as I said above, was easily accomplished in manner similar to what you did for `target` attribute).

AFAICT, the difficulty comes down to the fact that the renderer [doesn't export `MARKUP_TYPES`](https://github.com/bustle/mobiledoc-dom-renderer/blob/master/lib/utils/tag-names.js#L20) which is used to determine `isValidMarkerType` for the renderer.

I've already [opened a PR to add `<small>` to the list](https://github.com/bustle/mobiledoc-dom-renderer/pull/55) and left my [2 cents](https://github.com/bustle/mobiledoc-kit/issues/451#issuecomment-386847069) on the issue I found about making it easier to add tags to your editor/renderer.

**Comment by sdhull** [comment]
@ef4 @mixonic @bantic do you happen to know how actively mobiledoc is being maintained? Seems like activity here has dropped off a bit. I'm trying to figure out if my PR might get accepted/changes requested or if I'm kinda throwing stuff into /dev/null  🤔

**Comment by ef4** [comment]
I'm definitely still using it and relying on it, I just haven't had any issues lately where I've needed to go upstream.

Happy to help at whatever level of delegation makes sense to the current maintainers.

**Comment by sdhull** [comment]
@ef4 it's truly reassuring to hear that you are still using mobiledoc without issues. That really makes me feel better about choosing it.

It's such a cool project, I would really like to be a part of it. However I also don't want to work on PRs to improve APIs, docs, etc if my PRs won't be getting reviewed.

Over the past few weeks I've been poring over the docs & scouring issues on the 4 relevant repos. Looking for solutions to the problems I've run into but also just looking for signs of life. There is a definite dropoff in activity from maintainers over the past 1-2 years. The last edit to the [1.0 Roadmap doc](https://docs.google.com/document/d/1Tn3XdADu50Q0VStF5sIeUqlEDWqRJRX5-ZFwUKJ4ZS8/edit#) was in January 2017. The most recent comment I could find from a maintainer was [early March](https://github.com/bustle/ember-mobiledoc-editor/pull/148#issuecomment-370069398) of this year, saying they would fix CI.

I have a growing list of things I want to fix & improve but my priorities & level of documentation will be very different if I'm just doing it for myself, with no expectation to have stuff merged back upstream. That's why I'm trying to gauge level of commitment. Plus it would be nice to know where to go for help, or even if I can reasonably hope for help.

**Comment by sdhull** [comment]
Thanks @mixonic I've followed up off-thread. I've read through some threads about supporting different tags and I don't recall seeing cursor behavior come up but that totally makes sense.

Would love to be activating energy!  💫 I look forward to talking more with you about how I can best do that

**Comment by kevinansfield** [comment]
> Would love to be activating energy! 💫 I look forward to talking more with you about how I can best do that

I'd also like to join this effort 😄 Ghost will be launching the beta of our mobiledoc based editor today and hopefully having our final launch in a few months. I'm definitely all-in on mobiledoc and will be moving from building our functionality on top of mobiledoc to focusing on fixing issues and missing features in mobiledoc core.
